# Generated by Django 3.2.8 on 2021-10-08 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockQuotes', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
